#LogicParameter Settings
#Wed Apr 16 00:15:45 CEST 2025
AcceptEula=false
ChangePadletToHour=false
ClickVolume=0.75
Gamer=true
GlobalVolume=0.75
HoverVolume=0.75
IsFinish=false
IsInProgress=true
IsNotStarted=true
MusicVolume=0.0
PadletAfternoon=2
PadletDefault=1
PadletMorning=1
PadletNight=3
Ram=4096
RefreshTheToken=true
SaveServ=true
disposeframetolaunch=false
